# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eC_C00Tzl1gauhJi518Up3byCZmrusv0

task 1
"""

a=("I am signing up for Replit's 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.No excuses for not coding from the middle of a field!")
print(a)

malware={'ransomeware':'RYUK','fileless':'Astaroth','spyware':'Darkhotal','adware':'fireball'}

print(malware)

print(malware.values())

print(malware.items())

print(malware.keys())

print(malware.clear())

"""task 2"""

O_prize=12300;
GST=(12300 * 18 / 100);
print("GST:", GST )
print(O_prize + GST)

"""task 3"""



"""task 4"""

import pandas as pd
student_data=pd.DataFrame(
    {"Student_Name": ["Rajesh", "Vishnu", "Yogeshpandian", "Kottai", "Yogeshwaran", "Gulfum", "Boobathy", "Goodson", "Periyasamy", "Murali"],
     "Age": [20,20,20,20,20,20,20,20,20,20],
     "DOB(year)": [2001,2001,2001,2001,2001,2001,2001,2001,2001,2001],
     "Weight(kg)" : [60,62,75,80,49,67,83,66,73,72],
     "Height(cm)" : [150,120,135,177,156,188,199,154,177,133]}
)

student_data["BMI"]=student_data["Weight(kg)"]/student_data["Height(cm)"]*student_data["Height(cm)"]

student_data["Status"]=student_data["BMI"].apply(lambda x: "Normal" if x>50 and x<80 else "Underweight")
# print(student_data)


student_data.to_csv("student_data.csv")
student_data=pd.read_csv("/content/student_data.csv")
student_data

"""task 5"""

print("\t\t\tcalculating EB bill")
type=int(input("\n select the residntial palce:\n\n1.household\n2.commercial\n"))
if(type ==1):
  def house():
    print("EB Bill for your House:")
    
    unit=int(input("enter the units:"))
    if(unit<=100):
        ui=unit*0.50
    elif unit>=101 and unit<200:
         ui=unit*0.75
    elif unit<201 and unit<300:
         ui=unit*1.20
    elif unit>300:
         ui=unit*1.50    
    
    print("total charges:",ui)
  house()  

if(type ==2):
     def com():
      print("EB Bill for your Commercial palce:")
   
     unit=int(input("enter the units:"))
     if (unit<=100):
        ui=unit*0.50
     elif unit>=101 and unit<200:
         ui=unit*0.75
     elif unit<201 and unit<300:
         ui=unit*1.20
     elif unit>300:
         ui=unit*1.50    
     print("total charges:",ui)
     com()